### ISSUE TITLE
feature request: export web diff through CLI

### ISSUE THREAD

**Issue by hkennyv** [jupyter/nbdime#539] opened 2020-09-17 18:50 UTC
First, just wanted to thank the maintainers for this great tool. It's super helpful.

Currently, the only way (that I can find) to export the diff HTML is to run `nbdiff-web` and then click the `Export Diff` button in the browser.

It'd be really great to have a CLI flag or option that we can pass that will just output the HTML diff locally somewhere. This way, I don't really have to open a browser or anything to look at it and I can easily share it with others. I could see some really creative ways to incorporate this into CI or even have a bot that posts a link to the page somewhere in a PR thread or something.

I'd be happy to contribute this myself too if someone can point me in the right direction :+1:

**Comment by vidartf** [comment] 2020-09-18 12:29
Thanks for the kind words 😃 I believe this is a duplicate of https://github.com/jupyter/nbdime/issues/468 ? There are also some suggestions in there for various ways such a feature can be implemented, I believe.

**Closed** 2020-09-18 12:30 UTC
