### ISSUE TITLE
Cell height maxes out at 45 lines

### ISSUE THREAD

**Issue by auneri** [jupyter/nbdime#388] opened 2018-06-12 23:31 UTC
Cells containing more than 45 lines start scrolling.
Observed in JupyterLab v0.32.1, only when nbdime extension is installed and enabled.

**Comment by vidartf** [comment] 2018-06-13 11:39
The maximum height is set relative to the maximum of the view port height. The rational behind this is to allow any horizontal scroll bar to be visible in the view without having to scroll all the way to bottom. Do you have any specific input in how you would expect it to behave for the four cases:
- entire content fits in allocated space
- content overflows horizontally
- content overflows vertically
- content overflows both horizontally and vertically

These are design decisions where it can be hard to accommodate all scenarios (but I'm open to good ideas!).

**Comment by auneri** [comment] 2018-06-14 23:38
Just to be clear, the height limit is observed in the standard notebook cells, not the diffs views.

I would be surprised if that was also intentional, since it doesn't seem to be related or necessary for the "diffing and merging of jupyter notebooks" (which is super-useful btw).

**Comment by vidartf** [comment] 2018-06-15 09:40
Could you post a screenshot of what you mean? I think see the same behavior with jupyterlab when simply editing a normal cell (although I see a limit of ~70 lines). As nbdime uses jupyterlab's rendering mechanisms for any non-diffed cell, it will follow whatever jupyterlab does.

Also, as this is a little hard issue to talk about, I tried to break down the questions that would be needed to be answered to change this behavior in my last comment. If you want this changed, I'd love to have your input on this. In general, saying what you think is wrong is a lot less useful than saying what you think would be a better way 😄

**Comment by vidartf** [comment] 2018-09-03 13:01
Closing due to lack of input/reproducibility. Will be happy to reopen if more input is given (e.g. a more detailed description of the issue, preferably with one or more screenshots).

**Closed by vidartf** 2018-09-03 13:01 UTC
