### ISSUE TITLE
problems in diff 2 files using nbmerge-web

### ISSUE THREAD

**Issue by shacharp** [jupyter/nbdime#523] opened 2020-05-08 15:46 UTC
Hi,

I have some dozens files and I started diff them.
After 5-6 diffs, the system couldn't diff anymore, and when I tried again it shows me this message:
![image](https://user-images.githubusercontent.com/49400601/81422711-05e2f480-915c-11ea-95b6-944ccf030c4a.png)

The web interface is appearing for 1-2 seconds, I can see it's written that it can't fetch, then it closes.

I've tried event to diff files that I've compared before and it was fine, but they fail also.

EDIT:
If I deactivate conda's env, and activating it again, this fixes the issue.
Still, wierd.

**Comment by vidartf** [comment] 2020-05-12 13:51
Thanks for the report and the update. I agree this is a strange error, but it seems to be caused by something else than nbdime, so will close this for now.

**Closed by vidartf** 2020-05-12 13:51 UTC
