### ISSUE TITLE
Git button is disabled after following nbdime installation instructions

### ISSUE THREAD

**Issue by orome** [jupyter/nbdime#537] opened 2020-08-25 16:06 UTC
Following installation of nbdime, the git button in Jupyter Lab notebooks is disabled. Hovering over the button now shows 

> Display nbdiff from git HEAD ...

but clicking the button has no effect. Diffs from within the git UI in the sidebar work correctly however.

jupyterlab 2.2.6

**Comment by vidartf** [comment] 2020-09-18 12:32
This is probably caused by the bug here: https://github.com/jupyter/nbdime/issues/531 Closing as a duplicate. Please comment if you believe this issue to a separate problem.

**Closed by vidartf** 2020-09-18 12:32 UTC

**Comment by orome** [comment] 2020-09-18 15:01
@vidartf  Maybe; we'll see.
