### ISSUE TITLE
Can merge/diff driver compare notebooks based on cell ID?  

### ISSUE THREAD

**Issue by qwjlegend** [jupyter/nbdime#448] opened 2019-02-05 00:05 UTC
Current the merge driver seems to always compare conflicting notebooks from the bottom cell to the up cell, is it possible to compare based on cell ID? (https://github.com/NII-cloud-operation/Jupyter-LC_nblineage)

**Comment by vidartf** [comment] 2019-02-05 09:49
Hi! I see two points mentioned in this issue, so I'll try to address them separately:

1:
> Current the merge driver seems to always compare conflicting notebooks from the bottom cell to the up cell.

Do you have a set of example notebooks you could share to demonstrate what you mean? Adding problematic notebook sets to our test-suite is a continuous effort that should help improve the overall quality of nbdime (independent of how it is solved).

2:
> is it possible to compare based on cell ID? (https://github.com/NII-cloud-operation/Jupyter-LC_nblineage)

I have no idea if this is possible or not. I'm struggling to get an overview of the cell IDs from a quick look at the documentation. If it turns out that using the IDs can robustly help resolve diffs and merge conflicts then this might be a good bonus feature for those who use these IDs for their notebooks. Whether that functionality should be in nbdime, or is best served in an application that uses nbdime as a library is not immediately clear to me.

**Comment by qwjlegend** [comment] 2019-02-05 19:46
Hi, thanks for getting back, here are the examples:
Merging notebook1 and notebook2 results in notebook3:
<img width="186" alt="conf1" src="https://user-images.githubusercontent.com/19258559/52299769-23168b00-293b-11e9-9cac-4870fdd5f8da.png">
<img width="141" alt="conf2" src="https://user-images.githubusercontent.com/19258559/52299802-3295d400-293b-11e9-962e-2870df8615ec.png">
<img width="421" alt="conf12" src="https://user-images.githubusercontent.com/19258559/52299804-3590c480-293b-11e9-89d7-06d8f2fe2085.png">
I've tried multiple examples, seems it always compare starting from the bottom cell to the upper cell.

**Comment by vidartf** [comment] 2019-02-06 08:53
What is the base notebook of this merge?

**Comment by qwjlegend** [comment] 2019-02-06 22:07
This the base:
<img width="153" alt="base" src="https://user-images.githubusercontent.com/19258559/52377007-7e6a7b00-2a18-11e9-9703-e738da45c4ee.png">

**Comment by vidartf** [comment] 2019-02-07 09:12
I'm sorry, but I'm not able to reproduce the behavior locally. The set of base/local/remote that you outline should not even give a merge conflict in the first place. Would it be possible for you to list the steps to reproduce this in more detail? And ideally how you would expect your final notebook to look.

**Comment by vidartf** [comment] 2020-03-09 15:28
Closing as missing reproduction of issue. Feel free to comment further if you can share a clear reproduction case (i.e. notebooks files for base/local/remote, and which nbdime versions that has the issue).

**Closed by vidartf** 2020-03-09 15:28 UTC
