### ISSUE TITLE
nbdime enable --sys-prefix doesn't work

### ISSUE THREAD

**Issue by jabbera** [jupyter/nbdime#575] opened 2021-03-19 16:48 UTC
using 3.0.0b1 and JL 3.0.11 you can't enable the extension with:
```
nbdime enable --sys-prefix
```

The command fails because labextension enable doesn't take the argument --sys-prefix:

https://github.com/jupyter/nbdime/blob/f6beb6001537bba841625b5cc7011dd5d4fec536/nbdime/__main__.py#L55

**Comment by vidartf** [comment] 2021-04-12 11:01
Thanks. Closing as a duplicate of https://github.com/jupyter/nbdime/issues/479 .

**Closed by vidartf** 2021-04-12 11:01 UTC
