### ISSUE TITLE
nbdime with plotly creates huge commit diffs

### ISSUE THREAD

**Issue by lytex** [jupyter/nbdime#520] opened 2020-04-09 17:10 UTC
Using nbdime and [plotly](https://github.com/plotly/plotly.py) results in huge commit diffs because all the plotly javascript code is considered in each commit. However if we embed the plotly figures into the notebook (as matplotlib does) nbdime tracks only the python code that is changing.
I've created an [example github repository](https://github.com/lytex/plotly_nbdime_test) to show the issue.

**Comment by vidartf** [comment] 2020-04-29 14:39
I'm not sure if I fully understand what you are describing. Would you mind sharing a screenshot of a how things look when you get the huge commit diff?

**Comment by lytex** [comment] 2020-04-30 17:10
Cloning the repository and writing the diff to a file (using nbdime)

```
git clone https://github.com/lytex/plotly_nbdime_test
git diff ec5ad94 41f926c > test.txt
$ ls -lh test.txt
-rw-rw-r-- 1 julian julian 3.2M abr 30 19:01 test.txt
```
The notebook code only changes slightly:
`fig = px.line([1, 2, 3], [1, 1, 1]) -> fig = px.line([1, 2, 3], [1, 2, 1])`
but because plotly uses javascript to generate an interactive notebook image

Probably the issue has more to do with plotly/ipython interaction, and a possible solution would be writing a suitable ipython magic`%plotly inline` similar to matplotlib's, to have the plotly figures rendered as images embedded in the notebook.
I've opened an issue in plotly:
[ihttps://github.com/plotly/plotly.py/issues/2411)](https://github.com/plotly/plotly.py/issues/2411)

Still, it would be possible to write a quick workaround for this particular case?

**Comment by lytex** [comment] 2020-04-30 18:23
Using IPython magic, it could be simply:

```
from IPython.core.magic import register_line_magic
from IPython.display import Image

@register_line_magic
def plotly_inline(plotly_figure):
    display(Image(eval(plotly_figure).to_image()))

import plotly.express as px
fig = px.line([1, 2, 3], [1, 2, 1])
%plotly_inline fig
# Displays figure as an image
```

**Comment by vidartf** [comment] 2020-05-04 10:15
Ah, ok. So the diff is actually huge (the output from plotly has changed greatly). A normal text diff ends up being enormous as well. The only real solution at the moment would be to ignore outputs for diffs entirely (either using the `--ignore-outputs` flag, or by config).

A possible improvement would be to add a config/flag for the diff CLIs (nbdiff + VCS wrappers) along the lines of "maximum output diff display length" (naming is hard). If set, it would crop the length for output diffs.

**Comment by lytex** [comment] 2020-05-08 04:33
A plotly collaborator posted a solution in the [plotly issue](https://github.com/plotly/plotly.py/issues/2411) (haven't tested yet), and I also came up with another possible solution involving `IPython.display.Image` and creating a custom plotly line magic

**Comment by vidartf** [comment] 2020-10-02 13:56
Closing this in favor of #530, as that should resolve this issue (and without such an option I would say this is working as intended).

**Closed by vidartf** 2020-10-02 13:56 UTC
