### ISSUE TITLE
CM6: Several conflict gutter markers placed on the same line

### ISSUE THREAD

**Issue by HaudinFlorence** [jupyter/nbdime#700] opened 2023-10-02 13:29 UTC
When trying to run example6, the following issue has been observed in the merge editor: several conflict gutter markers are produced at the same line (case of line 6), not placed exactly at the same location.

![Screenshot from 2023-10-02 15-24-57](https://github.com/jupyter/nbdime/assets/99649086/a4f0386b-9d08-4119-b893-4d59fa23c7fa)

**Comment by krassowski** [comment] 2023-10-20 21:25
I was able to reproduce it, specifically, it looks that there are two copies of the marker in line 5:

![image](https://github.com/jupyter/nbdime/assets/5832902/a2748516-9b6e-470e-a10b-7d57300bd7fc)

and the second copy overhangs to line 6.

**Comment by krassowski** [comment] 2023-10-20 21:57
Well, I am not sure if the issue is in the gutter code or in the chunking algorithm. In this case we get 6 conflict chunks:

![image](https://github.com/jupyter/nbdime/assets/5832902/5026caf4-84f8-4d01-9d28-6f3f3fb06413)

And two of them have `remoteFrom: 4` (so start at line 5, and the second of these leads to overhanging into line 6).

The also seem essentially identical:

| First copy | Second copy |
|--------|--------|
| ![Screenshot from 2023-10-20 22-54-47](https://github.com/jupyter/nbdime/assets/5832902/cdb4aace-942b-4667-a969-46b5fe05422e) |![Screenshot from 2023-10-20 22-54-38](https://github.com/jupyter/nbdime/assets/5832902/117f921a-f967-44c0-92b5-d7861f58ab6f) | 

Is there any case when duplicate chunks are expected, or is this an error in chunking code?

**Comment by krassowski** [comment] 2023-10-20 21:59
> Is there any case when duplicate chunks are expected, or is this an error in chunking code?

@vidartf is this what you meant by "In certain cases overlapping chunks are not being considered properly overlapping." in issue https://github.com/jupyter/nbdime/issues/677? In that case I think this issue just becomes a duplicate of #677.

**Comment by HaudinFlorence** [comment] 2023-10-21 12:05
> Well, I am not sure if the issue is in the gutter code or in the chunking algorithm. In this case we get 6 conflict chunks:
> 
> ![image](https://user-images.githubusercontent.com/5832902/277058062-5026caf4-84f8-4d01-9d28-6f3f3fb06413.png)
> 
> And two of them have `remoteFrom: 4` (so start at line 5, and the second of these leads to overhanging into line 6).
> 
> The also seem essentially identical:
> 
> First copy	Second copy
> ![Screenshot from 2023-10-20 22-54-47](https://user-images.githubusercontent.com/5832902/277058969-cdb4aace-942b-4667-a969-46b5fe05422e.png)	![Screenshot from 2023-10-20 22-54-38](https://user-images.githubusercontent.com/5832902/277058968-117f921a-f967-44c0-92b5-d7861f58ab6f.png)
> Is there any case when duplicate chunks are expected, or is this an error in chunking code?

@krassowski In fact that's what I have been observed but I have not been able to go really further.

**Comment by vidartf** [comment] 2023-11-06 16:55
There does seem to be a regression here compared to CM5 version. See this example diffing the files in ui-test/data/merge_test1:

CM5:
![image](https://github.com/jupyter/nbdime/assets/510760/5e97217c-d23a-40e3-adbb-4c125803b54a)

CM6:
![image](https://github.com/jupyter/nbdime/assets/510760/2634c8d1-abfc-4c53-98eb-0e35124c6939)

Notice the extra arrow on the base version on line 5. You can also see the same for CM6 here: 

https://github.com/jupyter/nbdime/blob/554c2d34882c77ce48e85586f5db8fce93ed80d1/ui-tests/tests/nbdime-merge-test1.spec.ts-snapshots/merge-test1-take-a-snapshot-at-opening-1-linux.png

**Comment by krassowski** [comment] 2023-11-06 16:58
Yes, but it is not a bug in CM6 but a bug in how the chunks are calculated as per my comments above.

**Comment by krassowski** [comment] 2023-11-06 17:05
Of course it still should be fixed, which may be best approached by writing a test case, but it may require more thought/context to understand why the chunking algorithm sometimes leads to duplicate chunks; or we could just add a simple workaround of de-duplicating them without worrying about the algorithm being occasionally wrong.

**Comment by vidartf** [comment] 2023-11-06 17:06
To clarify, I am using CM5/CM6 as a shorthand for "current stable release" vs "current RC".

**Comment by vidartf** [comment] 2023-11-06 17:08
(and while there are for sure some bugs in the current stable version's chunking algorithm, the one I point out above is a new bug in the RC version)

**Closed** 2023-11-10 23:30 UTC
