### ISSUE TITLE
nbmerge-web throws "Invalid cell decision" and "c is undefined"

### ISSUE THREAD

**Issue by antonbabkin** [jupyter/nbdime#345] opened 2018-03-08 18:23 UTC
I am trying to do a simple notebook merge, and web tool for conflict resolution does not work as I want it to. I am not sure if it's a bug, or I am just using it wrong.
Version:
```bash
nbdime --version
0.4.1
```

I have a simple [git repo](https://github.com/antonbabkin/nbdime-demo).

Initial commit only has one markdown cell. Development further diverges into "alice" and "bob" branches, reflecting parallel development of independent features. Each branch adds a single markdown cell. After that, branches must be merged.

Merged notebook should have 3 markdown cells.
1. First cell from "master" (base).
2. Second cell from "alice".
3. Third cell from "bob".

Here is what I do:
```bash
nbdime config-git --enable
git checkout bob
git merge alice
# conflicts occured
nbdime mergetool
```
Web tool opens, I see first cell as unchanged, then bob's cell as local and then alice's cell as remote, in that order, no parallel cells. I want to simply reorder them, so I drag alice's cell above bob's. Then I press "Save" button, but nothing happens. In browser console this error appears:
```
Error: Invalid cell decision    exceptions.ts:15:4
NotifyUserError   exceptions.ts:15:4
CellMergeModel.prototype.serialize    cell.ts:333:14
NotebookMergeModel.prototype.serialize    notebook.ts:115:15
extractMergedNotebook    save.ts:23:11
saveMerged.   merge.ts:192:11
```

If I then press "Download", I get this error:
```
TypeError: c is undefined [Learn More]    notebook.ts:130:6
get    notebook.ts:130:6
get    notebook.ts:138:19
downloadMerged    merge.ts:245:6
```

Nothing happens with the notebook, and so the merge conflict is not resolved.

`nbdiff` and `nbdiff-web` work fine. Here's the diff of alice and bob.
```
nbdiff 33e7 0e66
nbdiff main.ipynb (33e7) main.ipynb (0e66)
--- main.ipynb (33e7)  (no timestamp)
+++ main.ipynb (0e66)  (no timestamp)
## inserted before /cells/1:
+  markdown cell:
+    source:
+      # Chapter 1.
+      Alice works hard.

## deleted /cells/1:
-  markdown cell:
-    source:
-      # Chapter 2.
-      Bob hardly works.
```

**Comment by vidartf** [comment] 2018-03-09 09:48
Thanks for the clear explanation and demo repo! I'll have a look.

**Comment by vidartf** [comment] 2018-03-09 13:32
Troubleshooting log for internal reference:
- This case seems to have fallen through the cracks after adding support for matching similar adds in generic merge. There wasn't a corresponding update to the mergetool for cells.
- The immediate cause of the symptom is that the split decision actions are marked as "base" instead of "local" and "remote". Updating the decision actions should fix the error.
- Given that these were marked as similar additions, we could've done a full side-by-side rendering, but this has previously been explicitly avoided to keep things simple. In the future we could look at how the inline merge handles this in order to do such a "base-less" side by side.
- The chunk of the similar added cells should probably get some color coding to help guide the user to the cause of the conflict. Maybe coloring the cells headers. We also need to have the user explicitly mark the conflict as resolved.

**Comment by antonbabkin** [comment] 2018-03-09 18:13
Here's also a related question.
I my example, I wanted to have alice's and bob's cells to be independent and sequential, so merge should put them one after the other. What if I instead wanted to combine them into one single cell that has some combination of two cells' texts in it? How does nbdime decide whether two cells should be kept separate or joined into one?

**Comment by vidartf** [comment] 2018-03-12 10:12
> How does nbdime decide whether two cells should be kept separate or joined into one?

It uses an "edit distance" metric to determine how similar they are, and a heuristic value for a threshold to determine if they are similar enough to be considered one to be a modification of the other. In this case, nbdime has actually decided they are similar (which is why it is marked as a conflict).

> What if I instead wanted to combine them into one single cell that has some combination of two cells' texts in it?

Currently, the only way is to keep both cells and then open the notebook for editing, and manually merging the contents. Preferably, this should be easier, which is what I'm working on now:
- The intermediate notebook saved after conflicts have been detected should include only one conflicted cell, with inline strategy for all content (i.e. with conflict markers in source/output).
- The mergetool should allow for manual editing, and maybe line them up against each other.

At least one of the two options should be available, I would say.

**Comment by vidartf** [comment] 2018-03-12 10:15
> In this case, nbdime has actually decided they are similar (which is why it is marked as a conflict).

Actually this is not necessarily true, I missed a code path. It does however have the capability of figuring this out. Hopefully this is feasible to sort out.

**Comment by antonbabkin** [comment] 2018-03-12 15:40
Thanks for the clarification, manually editing notebook with inline conflicts either inside or outside of mergetool both sound like reasonable options.

I also have a suggestion about deciding if it's same cell with different content, or two different cells. nbdime can use it's heuristics to make the best guess, but then during conflict resolution in nbmerge-web, user might be given an opportunity to change nbdime's decision: Either drag two combined cells apart, or drag two separated cells on top of each other. Don't know if it's feasible to implement, but I'd be happy to see such flexibility.

**Comment by vidartf** [comment] 2018-03-13 14:20
FYI: I added some initial work for point (1.) above in #347. It include as screenshot of how your example repo would be handled.

**Closed** 2018-03-14 15:50 UTC
